---
version: '3.7'
services:

  prometheus:
    image: prom/prometheus:v2.47.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/chargecode_prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
    - 9090:9090
    expose:
    - 9090

  grafana:
    image: grafana/grafana:10.2.0
    volumes:
      - grafana_data:/var/lib/grafana
      - ./kafka/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pfsecret
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
    - 3000:3000
    expose:
      - 3000

volumes:
    prometheus_data: {}
    grafana_data: {}

