global:
  scrape_interval:     15s
  evaluation_interval: 15s

#rule_files:
#  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'kafka-broker'
    scrape_interval: 5s
    metrics_path: /
    file_sd_configs:
      - files:
          - 'targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    metric_relabel_configs:
      - source_labels: ['cluster', 'topic']
        separator: '_'
        target_label: chargecode
        regex: '^monitoring-msk_demo(.*)$'
        replacement: 'application'
      - source_labels: ['cluster', 'topic']
        separator: '_'
        target_label: chargecode
        regex: '^monitoring-msk_test(.*)$'
        replacement: 'analytics'
      - source_labels: ['cluster', 'client_id']
        separator: '_'
        target_label: chargecode
        regex: '^monitoring-msk_demo(.*)$'
        replacement: 'analytics'
      - source_labels: ['cluster', 'client_id']
        separator: '_'
        target_label: chargecode
        regex: '^monitoring-msk_test(.*)$'
        replacement: 'application'
