global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - ./rules.yml

scrape_configs:
  - job_name: 'kafka-broker'
    file_sd_configs: 
      - files: 
        - 'targets.json'
    static_configs:
      - labels:
          env: "dev"
          __name__: "availabitity_zone_cost"
          region: "us-east-1"
          src_availability_zone: "us-east-1f"
          dest_availability_zone: "us-east-1b"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: 'zookeeper'
    file_sd_configs:
      - files: 
        - 'zookeeper_targets.json'
    static_configs:
      - labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
        
# schema registry
# kafka connect
# ksqldb
