global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'kafka-broker'
    file_sd_configs: 
      - files: 
        - 'targets.json'
    static_configs:
      - labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
    metric_relabel_configs:
      - source_labels: ['cluster', 'client_id']
        target_label: region
      - source_labels: ['cluster', 'client_id']
        target_label: src_avialability_zone
      - source_labels: ['cluster', 'client_id']
        target_label: dest_avialability_zone


  - job_name: 'zookeeper'
    file_sd_configs:
      - files: 
        - 'zookeeper_targets.json'
    static_configs:
      - labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

