groups:
  - name: "Cross-Zone Data Transfer Charges"
    rules:
#      - record: consumer_client_byte_rate
#        expr: sum(rate(kafka_server_Fetch_byte_rate{client_id!~"^consumer-amazon.msk.*", job="kafka-broker", instance=~"$instance", env="$env"}[5m])) by (client_id)
#
#      - record: producer_client_byte_rate
#        expr: sum(rate(kafka_server_Produce_byte_rate{client_id!~"^producer.*", job="kafka-broker", instance=~"$instance", env="$env"}[5m])) by (client_id)

      - record: cross_zone_transfer_cost
        expr: |
          sum by (region, src_availability_zone, dest_availability_zone) (
            (
              sum(rate(kafka_server_Fetch_byte_rate{client_id!~"^consumer-amazon.msk.*", job="kafka-broker", instance=~"$instance", env="$env"}[5m]))
              +
              sum(rate(kafka_server_Produce_byte_rate{client_id!~"^producer.*", job="kafka-broker", instance=~"$instance", env="$env"}[5m]))
            )
            *
            (
              (region == "us-east-1" and src_availability_zone == "us-east-1a" and dest_availability_zone == "us-east-1b" * 0.01) 
            )
          )
        labels:
          region: "us-east-1"
          src_availability_zone: "us-east-1a"
          dest_availability_zone: "us-east-1b"
