{
 "title": "Cluster Utilization",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_Value{name=\"BrokerState\", env=\"$env\"},instance)"
    }
   },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_Log_Value,topic)"
    }
   },
   { "name": "group", "label": "Consumer Group", "query": { "query": "label_values(groupId)" } },
   {
    "name": "producer_client_id",
    "label": "Producer Client ID",
    "query": {
     "query": "label_values(kafka_server_Produce_byte_rate,client_id)"
    }
   },
   {
    "name": "consumer_client_id",
    "label": "Consumer Client ID",
    "query": {
     "query": "label_values(kafka_server_Fetch_byte_rate,client_id)"
    }
   },
   { "name": "convert_to_GB", "query": "1073741824" },
   {
    "name": "GB_Month",
    "query": {
     "query": "query_result($Days_in_month * 24)"
    }
   },
   { "name": "Days_in_month", "label": "Days_in_month", "query": "28,29,30,31" },
   { "name": "partition", "label": "Partition", "query": { "query": "label_values(partition)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"node\", env=~\"$env\", instance=~\"$instance\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Usage Per Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  { "title": "Thread Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Handler",
   "type": "timeseries",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 100 (all resources are are available). \\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - kafka_server_KafkaRequestHandlerPool_Count{name=\"RequestHandlerAvgIdlePercent\", job=\"kafka-broker\", env=~\"$env\", instance=~\"$instance\"}/10000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Processor Usage ",
   "type": "timeseries",
   "description": "Average fraction of time the network processor threads are idle. Values are between 0 (all resources are used) and 100 ( all resources are available)\\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\", job=\"kafka-broker\", env=~\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}