{
 "title": "Cost Center",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},partition)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_Value{name=\"BrokerState\", env=\"$env\"},instance)"
    }
   },
   {
    "name": "producer_client_id",
    "label": "Producer Client ID",
    "query": {
     "query": "label_values(kafka_server_Produce_byte_rate,client_id)"
    }
   },
   {
    "name": "consumer_client_id",
    "label": "Consumer Client ID",
    "query": {
     "query": "label_values(kafka_server_Fetch_byte_rate,client_id)"
    }
   },
   { "name": "convert_to_GB", "label": "convert_to_GB", "query": "1073741824" },
   { "name": "Days_in_month", "label": "Days_in_month", "query": "28,29,30,31" },
   {
    "name": "GB_Month",
    "label": "gb_month",
    "query": {
     "query": "query_result($Days_in_month * 24)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cost Center", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Broker",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Value{job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\", name=\"LeaderCount\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(client_id) (kafka_server_Fetch_byte_rate{client_id!~\"^consumer-amazon.msk.*\"})) + count(count by(client_id) (kafka_server_Produce_byte_rate{client_id!~\"^producer-.*\"}))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outbound Charges monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.09", "type": "math" }
   ]
  },
  {
   "title": "Storage Usage Cost Per Client(monthly)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.10", "type": "math" },
    { "expression": "$B * 0.10", "type": "math" }
   ]
  },
  {
   "title": "Storage Usage Per Partition",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.10", "type": "math" }
   ]
  },
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Storage Cost Per Instance (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.816", "type": "math" }
   ]
  },
  {
   "title": "Tiered Storage Cost Per Instance (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.060", "type": "math" }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Tiered Storage Cost Per Topic (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicAggregatedMetrics_Value{name=\"RemoteLogSizeBytes\", job=\"kafka-broker\", env=\"dev\", topic=~\"$topic\", instance=~\"$instance\"}[1h])) * $GB_Month / $convert_to_GB ",
     "legendFormat": "{{topic}}"
    },
    { "expression": "$A * 0.060", "type": "math" }
   ]
  },
  {
   "title": "Storage Usage Cost Per Topic (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.10", "type": "math" }
   ]
  }
 ]
}