{
 "title": "MSK_ResourceUsage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},partition)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_log_Log_Value{name=\"Size\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_KafkaServer_Value{name=\"BrokerState\",env=\"${env}\"}, instance)"
    }
   },
   {
    "name": "producer_client_id",
    "label": "Producer Client ID",
    "query": {
     "query": "label_values(kafka_server_Produce_byte_rate,client_id)"
    }
   },
   {
    "name": "consumer_client_id",
    "label": "Consumer Client ID",
    "query": {
     "query": "label_values(kafka_server_Fetch_byte_rate,client_id)"
    }
   },
   { "name": "convert_to_GB", "label": "convert_to_GB", "query": "1073741824" },
   { "name": "Days_in_month", "label": "Days_in_month", "query": "28, 29, 30, 31" },
   { "name": "Month", "query": { "query": "query_result(31*24)" } },
   {
    "name": "GB_Month",
    "query": {
     "query": "query_result($Days_in_month * 24)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cost Per Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Cost per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.816", "type": "math" }
   ]
  },
  {
   "title": "Tiered Storage Cost per Instance ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.060", "type": "math" }
   ]
  },
  { "title": "Cost Per Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage Cost Per Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.10", "type": "math" },
    { "expression": "$B * 0.10", "type": "math" }
   ]
  },
  { "title": "Cost Per Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Storage Cost Per  Partition ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(topic, partition) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\",partition=~\"$partition\"}[1h])) / $convert_to_GB / $GB_Month",
     "legendFormat": "{{topic}} @ partition-{{partition}}"
    },
    { "expression": "$A * 0.10", "type": "math" }
   ]
  },
  { "title": "Cost Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Storage Cost Per Topic ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.10", "type": "math" }
   ]
  },
  {
   "title": "Tiered Storage Cost per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.060", "type": "math" }
   ]
  },
  { "title": "Cost Center", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Instance charge monthly",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.816", "type": "math" }
   ]
  },
  {
   "title": "Storage Provision Throughput (MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", job=\"kafka-broker\", env=\"$env\", instance=~\"b-1.monitoringmsk.wlkexu.c18.kafka.us-east-1.amazonaws.com\"}[1m])) / 1024 / 1024",
     "legendFormat": "Total_inbound"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", job=\"kafka-broker\", env=\"$env\", instance=~\"b-1.monitoringmsk.wlkexu.c18.kafka.us-east-1.amazonaws.com\"}[1m])) / 1024 / 1024",
     "legendFormat": "Total_outbound"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Outbound Charges (monthly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$A * 0.09", "type": "math" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Number of clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(client_id) (kafka_server_Fetch_byte_rate{client_id!~\"^consumer-amazon.msk.*\"})) + count(count by(client_id) (kafka_server_Produce_byte_rate{client_id!~\"^producer-.*\"}))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Number of Partition",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalPartitionCount\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\"})",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Storage Used Per Partition (GB-month)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic, partition) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\",partition=~\"$partition\"}[1h])) / $convert_to_GB / $GB_Month",
     "legendFormat": "{{topic}} @ partition-{{partition}}"
    }
   ]
  },
  {
   "title": "Storage Used Per Topic(GB-month)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Topic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Broker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Value{job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\", name=\"LeaderCount\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining Storage (GB-month)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", cluster=~\"monitoring-msk\", env=\"dev\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "__auto"
    },
    { "expression": "300 - $TotalStorage", "type": "math" }
   ]
  },
  {
   "title": "Storage User Per Instance (GB-month)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Usage per client (GB-month)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(client_id) (rate(kafka_server_Fetch_byte_rate{client_id=~\"$consumer_client_id\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{client_id}}"
    },
    {
     "expr": "sum by(client_id) (rate(kafka_server_Produce_byte_rate{client_id=~\"$producer_client_id\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Storage Usage Per Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Low-cost Tier Storage (GB-month)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicAggregatedMetrics_Value{name=\"RemoteLogSizeBytes\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\"}[1h])) * (30*24) / $convert_to_GB",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Used Per Instance (GB-month)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", instance=~\"$instance\", env=\"dev\", cluster=~\"$cluster\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low-cost tier Storage (Byte/hour-month)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicAggregatedMetrics_Value{name=\"RemoteLogSizeBytes\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\"}[1h])) * $Month",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Used Per Instance (GB-hour)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", cluster=~\"$cluster\"}[1h])) / $convert_to_GB",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Storage Usage Per Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Storage User Per Partition (GB-month)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(partition, topic) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\",partition=~\"$partition\"}[1h]))/$convert_to_GB / $Month",
     "legendFormat": "{{topic}} @ {{partition}}"
    }
   ]
  },
  {
   "title": "Storage User Per Partition(GB-hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(partition, topic) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", instance=~\"$instance\", env=~\"dev\", topic=~\"$topic\",partition=~\"$partition\"}[1h]))/$convert_to_GB",
     "legendFormat": "{{topic}} @ partition-{{partition}} "
    }
   ]
  },
  { "title": "Storage Usage Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Low-cost tiered storage (GB-month)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicAggregatedMetrics_Value{name=\"RemoteLogSizeBytes\", job=\"kafka-broker\", env=\"dev\", topic=~\"$topic\", instance=~\"$instance\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Low-cost tiered storage (Byte/hours-months)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_BrokerTopicAggregatedMetrics_Value{name=\"RemoteLogSizeBytes\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\"}[1h])) * $Month",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Storage User Per Topic (GB-month)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\"}[1h])) / $convert_to_GB / $Month",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Storage Used Per Topic (GB-hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_log_Log_Value{name=\"Size\", job=\"kafka-broker\", env=\"dev\", instance=~\"$instance\", topic=~\"$topic\"}[1h])) / $convert_to_GB",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}